## Classification

In [74]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import pickle

In [133]:
# feature selection
def selectkbest(indep_x,dep_y,n):
    test=SelectKBest(score_func=chi2,k=n)
    fit1=test.fit(indep_x,dep_y)    # fit - learns which features are important features 
    seleted_features=fit1.transform(indep_x)     #transform - select those features 
    # seleted_features = test.fit_transform(indep_x,dep_y)        # fit & transform in one step 
    return seleted_features

# tran test split and standardization 
def split_scaler(indep_x,dep_y):
    x_train,x_test,y_train,y_test = train_test_split(indep_x,dep_y,test_size=0.20,random_state=0)
    # standardization
    sc=StandardScaler()
    x_train=sc.fit_transform(x_train)
    x_test=sc.transform(x_test)
    return  x_train,x_test,y_train,y_test

# model prediction & evaluation 
def cm_pred_eval(classifier,x_test):
    # prediction
    y_pred=classifier.predict(x_test)
    # confusion matrix
    from sklearn.metrics import confusion_matrix
    cm=confusion_matrix(y_test,y_pred)
    # classification report 
    from sklearn.metrics import classification_report
    classi_report=classification_report(y_test,y_pred)
    # accuracy 
    from sklearn.metrics import accuracy_score
    accuracy=accuracy_score(y_test,y_pred)
    return classifier,accuracy,cm,classi_report,x_test,y_test

### --------------- classification algortihms -----------------------------
# logistic regression 
def logistic(x_train,y_train,x_test):
    # model creation
    from sklearn.linear_model import LogisticRegression
    classifier=LogisticRegression(random_state=0)
    classifier.fit(x_train,y_train)
    # model prediction & evaluation
    classifier,accuracy,cm,classi_report,x_test,y_test = cm_pred_eval(classifier,x_test)
    return classifier,accuracy,cm,classi_report,x_test,y_test

# KNN 
def knn(x_train,y_train,x_test):
    # model creation
    from sklearn.neighbors import KNeighborsClassifier
    classifier=KNeighborsClassifier(n_neighbors=5,p=2, metric='minkowski')
    classifier.fit(x_train,y_train)
    # model prediction & evaluation
    classifier,accuracy,cm,classi_report,x_test,y_test = cm_pred_eval(classifier,x_test)
    return classifier,accuracy,cm,classi_report,x_test,y_test

# SVM - linear 
def svm_linear(x_train,y_train,x_test):
    # model creation
    from sklearn.svm import SVC
    classifier=SVC(kernel='linear',random_state=0)
    classifier.fit(x_train,y_train)
    # model prediction & evaluation
    classifier,accuracy,cm,classi_report,x_test,y_test = cm_pred_eval(classifier,x_test)
    return classifier,accuracy,cm,classi_report,x_test,y_test

# SVM - Non linear 
def svm_nonlinear(x_train,y_train,x_test):
    # model creation
    from sklearn.svm import SVC
    classifier=SVC(kernel='rbf',random_state=0)
    classifier.fit(x_train,y_train)
    # model prediction & evaluation
    classifier,accuracy,cm,classi_report,x_test,y_test = cm_pred_eval(classifier,x_test)
    return classifier,accuracy,cm,classi_report,x_test,y_test

# navie bayes
def naive(x_train,y_train,x_test):
    # model creation 
    from sklearn.naive_bayes import GaussianNB
    classifier=GaussianNB()
    classifier.fit(x_train,y_train)
    # model prediction & evaluation
    classifier,accuracy,cm,classi_report,x_test,y_test = cm_pred_eval(classifier,x_test)
    return classifier,accuracy,cm,classi_report,x_test,y_test

# decision tree
def decision_tree(x_train,y_train,x_test):
     # model creation 
    from sklearn.tree import DecisionTreeClassifier
    classifier=DecisionTreeClassifier(criterion='entropy',random_state=0)
    classifier.fit(x_train,y_train)
    # model prediction & evaluation
    classifier,accuracy,cm,classi_report,x_test,y_test = cm_pred_eval(classifier,x_test)
    return classifier,accuracy,cm,classi_report,x_test,y_test

# random forest
def random_forest(x_train,y_train,x_test):
     # model creation 
    from sklearn.ensemble import RandomForestClassifier
    classifier=RandomForestClassifier(n_estimators=10,criterion='entropy',random_state=0)
    classifier.fit(x_train,y_train)
    # model prediction & evaluation
    classifier,accuracy,cm,classi_report,x_test,y_test = cm_pred_eval(classifier,x_test)
    return classifier,accuracy,cm,classi_report,x_test,y_test


## ------------ final table for comparision

In [76]:
def selectk_classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf):
    dataframe=pd.DataFrame(index=['Chi square'],columns=['logistic','KNN','SVMl','SVMnl','NB','decision','random forest'])
    for number,idex in enumerate(dataframe.index):
        dataframe.loc[idex,'logistic']=acclog[number]
        dataframe.loc[idex,'KNN']=accsvml[number]
        dataframe.loc[idex,'SVMl']=accsvmnl[number]
        dataframe.loc[idex,'SVMnl']=accknn[number]
        dataframe.loc[idex,'NB']=accnav[number]
        dataframe.loc[idex,'decision']=accdes[number]
        dataframe.loc[idex,'random forest']=accrf[number]
        return dataframe

In [77]:
data_original = pd.read_csv('preprocessed_CKD.csv')
data_ckd= data_original
data_ckd

,age,bp,sg,al,su,bgr,bu,sc,sod,pot,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,48.0,80.0,1.020,1.0,0.0,121.0,36.0,1.2,138.0,4.4,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,7.0,50.0,1.020,4.0,0.0,121.0,18.0,0.8,138.0,4.4,...,38,6000,0.0,no,no,no,good,no,no,ckd
2,62.0,80.0,1.010,2.0,3.0,423.0,53.0,1.8,138.0,4.4,...,31,7500,0.0,no,yes,no,poor,no,yes,ckd
3,48.0,70.0,1.005,4.0,0.0,117.0,56.0,3.8,111.0,2.5,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,51.0,80.0,1.010,2.0,0.0,106.0,26.0,1.4,138.0,4.4,...,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,55.0,80.0,1.020,0.0,0.0,140.0,49.0,0.5,150.0,4.9,...,47,6700,4.9,no,no,no,good,no,no,notckd
396,42.0,70.0,1.025,0.0,0.0,75.0,31.0,1.2,141.0,3.5,...,54,7800,6.2,no,no,no,good,no,no,notckd
397,12.0,80.0,1.020,0.0,0.0,100.0,26.0,0.6,137.0,4.4,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,17.0,60.0,1.025,0.0,0.0,114.0,50.0,1.0,135.0,4.9,...,51,7200,5.9,no,no,no,good,no,no,notckd
399,58.0,80.0,1.025,0.0,0.0,131.0,18.0,1.1,141.0,3.5,...,53,6800,6.1,no,no,no,good,no,no,notckd

In [81]:
data_ckd=pd.get_dummies(data_ckd,drop_first=True,dtype=int)
data_ckd.head()

,age,bp,sg,al,su,bgr,bu,sc,sod,pot,...,dm_yes,cad_unknown,cad_yes,appet_poor,appet_unknown,pe_unknown,pe_yes,ane_unknown,ane_yes,classification_notckd
0,48.0,80.0,1.020,1.0,0.0,121.0,36.0,1.2,138.0,4.4,...,1,0,0,0,0,0,0,0,0,0
1,7.0,50.0,1.020,4.0,0.0,121.0,18.0,0.8,138.0,4.4,...,0,0,0,0,0,0,0,0,0,0
2,62.0,80.0,1.010,2.0,3.0,423.0,53.0,1.8,138.0,4.4,...,1,0,0,1,0,0,0,0,1,0
3,48.0,70.0,1.005,4.0,0.0,117.0,56.0,3.8,111.0,2.5,...,0,0,0,1,0,0,1,0,1,0
4,51.0,80.0,1.010,2.0,0.0,106.0,26.0,1.4,138.0,4.4,...,0,0,0,0,0,0,0,0,0,0

In [82]:
# ip op split 
indep_x=data_ckd.drop('classification_notckd',axis=1)
dep_y = data_ckd['classification_notckd']

In [128]:
# k best 
no_of_features = 6
kBest=selectkbest(indep_x,dep_y,no_of_features)
kBest

array([[1.21e+02, 3.60e+01, 1.20e+00, 4.40e+01, 7.80e+03, 5.20e+00],
       [1.21e+02, 1.80e+01, 8.00e-01, 3.80e+01, 6.00e+03, 0.00e+00],
       [4.23e+02, 5.30e+01, 1.80e+00, 3.10e+01, 7.50e+03, 0.00e+00],
       ...,
       [1.00e+02, 2.60e+01, 6.00e-01, 4.90e+01, 6.60e+03, 5.40e+00],
       [1.14e+02, 5.00e+01, 1.00e+00, 5.10e+01, 7.20e+03, 5.90e+00],
       [1.31e+02, 1.80e+01, 1.10e+00, 5.30e+01, 6.80e+03, 6.10e+00]])

In [130]:
test=SelectKBest(score_func=chi2,k=no_of_features)
fit1=test.fit(indep_x,dep_y)    # fit - learns which features are important features 
seleted_features=fit1.transform(indep_x)

important_features = indep_x.columns[fit1.get_support()]        # ''' selected important features '''
print(important_features)

'''
5 features -> Index(['bgr', 'bu', 'sc', 'pcv', 'wc'], dtype='object')
4 features -> Index(['bgr', 'bu', 'pcv', 'wc'], dtype='object')
3 features -> Index(['bgr', 'bu', 'wc'], dtype='object')
10 features ->  Index(['age', 'al', 'su', 'bgr', 'bu', 'sc', 'hemo', 'pcv', 'wc', 'rc'], dtype='object')
6 features -> Index(['bgr', 'bu', 'sc', 'pcv', 'wc', 'rc'], dtype='object')
'''

Index(['bgr', 'bu', 'sc', 'pcv', 'wc', 'rc'], dtype='object')

"\n5 features -> Index(['bgr', 'bu', 'sc', 'pcv', 'wc'], dtype='object')\n4 features -> Index(['bgr', 'bu', 'pcv', 'wc'], dtype='object')\n3 features -> Index(['bgr', 'bu', 'wc'], dtype='object')\n10 features ->  Index(['age', 'al', 'su', 'bgr', 'bu', 'sc', 'hemo', 'pcv', 'wc', 'rc'], dtype='object')\n6 features -> Index(['bgr', 'bu', 'sc', 'pcv', 'wc', 'rc'], dtype='object')\n"

In [134]:
acclog=[]
accsvml=[]
accsvmnl=[]
accknn=[]
accnav=[]
accdes=[]
accrf=[]

x_train,x_test,y_train,y_test=split_scaler(kBest,dep_y)   # (selected important features , target variable) 

# algorithms 
classifier,accuracy,cm,classi_report,x_test,y_test=logistic(x_train,y_train,x_test)
acclog.append(accuracy)
classifier,accuracy,cm,classi_report,x_test,y_test=knn(x_train,y_train,x_test)
accknn.append(accuracy)
classifier,accuracy,cm,classi_report,x_test,y_test=svm_linear(x_train,y_train,x_test)
accsvml.append(accuracy)
classifier,accuracy,cm,classi_report,x_test,y_test=svm_nonlinear(x_train,y_train,x_test)
accsvmnl.append(accuracy)
classifier,accuracy,cm,classi_report,x_test,y_test=naive(x_train,y_train,x_test)
accnav.append(accuracy)
classifier,accuracy,cm,classi_report,x_test,y_test=decision_tree(x_train,y_train,x_test)
accdes.append(accuracy)
classifier,accuracy,cm,classi_report,x_test,y_test=random_forest(x_train,y_train,x_test)
accrf.append(accuracy)


result = selectk_classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf)

In [107]:
result #5

           logistic   KNN    SVMl   SVMnl      NB decision random forest
Chi square    0.925  0.95  0.9375  0.8875  0.9125   0.9625        0.9875

In [114]:
result #4

           logistic    KNN   SVMl  SVMnl    NB decision random forest
Chi square   0.9125  0.925  0.925  0.875  0.85    0.925          0.95

In [119]:
result #3

           logistic     KNN  SVMl  SVMnl    NB decision random forest
Chi square   0.7875  0.7875  0.85  0.825  0.85   0.8375        0.8625

In [123]:
result #10

           logistic     KNN    SVMl  SVMnl      NB decision random forest
Chi square   0.9625  0.9875  0.9875  0.975  0.9375      1.0        0.9625

In [132]:
result #6

           logistic     KNN    SVMl SVMnl      NB decision random forest
Chi square     0.95  0.9625  0.9625  0.95  0.9375    0.975        0.9875

With 3 features, model accuracy was lower, indicating insufficient information.

With 5 and 6 features, most models, including Decision Tree and Random Forest, performed very well, achieving high accuracy while maintaining generalization.

With 10 features, Decision Tree reached 100% accuracy, which may indicate overfitting.
Therefore, for a balanced approach, selecting 5 or 6 top features is recommended. For maximum accuracy, 10 features can be used, but caution is needed due to potential overfitting. Cross-validation should be applied to confirm robustness.

## Regression

In [136]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest, chi2, RFE
import pickle
from sklearn.model_selection import train_test_split

In [151]:
# ------------------------------- functions  -------------------------------
# feature selection 
def select_k_best(indep_x,dep_y,n):
    test=SelectKBest(score_func=chi2,k=n)
    selected_features = test.fit_transform(indep_x,dep_y)
    return selected_features

# regression model predict & evaluation 
def r2_score_pred(regressor,x_test,y_test):
    y_pred=regressor.predict(x_test)
    from sklearn.metrics import r2_score
    r2_score=r2_score(y_test,y_pred)
    return r2_score 

# tran test split and standardization 
def split_scaler(indep_x,dep_y):
    x_train,x_test,y_train,y_test = train_test_split(indep_x,dep_y,test_size=0.20,random_state=0)
    # standardization
    sc=StandardScaler()
    x_train=sc.fit_transform(x_train)
    x_test=sc.transform(x_test)
    return  x_train,x_test,y_train,y_test
    
# regression algorithms 
# linear
def linear(x_train,y_train,x_test):
    from sklearn.linear_model import LinearRegression
    regressor=LinearRegression()
    regressor.fit(x_train,y_train)
    r2 = r2_score_pred(regressor,x_test,y_test)
    return r2 
    
# SVR -linear
def svrl(x_train,y_train,x_test):
    from sklearn.svm import SVR
    regressor=SVR(kernel='linear')
    regressor.fit(x_train,y_train)
    r2 = r2_score_pred(regressor,x_test,y_test)
    return r2 
    
# SVR-non linear
def svrnl(x_train,y_train,x_test):
    from sklearn.svm import SVR
    regressor=SVR(kernel='rbf')
    regressor.fit(x_train,y_train)
    r2 = r2_score_pred(regressor,x_test,y_test)
    return r2 
    
# decision tree
def decisionReg(x_train,y_train,x_test):
    from sklearn.tree import DecisionTreeRegressor
    regressor=DecisionTreeRegressor(criterion='squared_error',random_state=0)
    regressor.fit(x_train,y_train)
    r2 = r2_score_pred(regressor,x_test,y_test)
    return r2 
    
# random forest 
def randomForestReg(x_train,y_train,x_test):
    from sklearn.ensemble import RandomForestRegressor
    regressor=RandomForestRegressor(n_estimators=10,random_state=0)
    regressor.fit(x_train,y_train)
    r2 = r2_score_pred(regressor,x_test,y_test)
    return r2 


# select features table 
def select_k_regression(acclinear,accsvrl,accsvrnl,accdes,accrf):
    dataframe=pd.DataFrame(index=['chi square'],columns=['linear','svrl','svrnl','decisionReg','randomForestReg'])
    for number,idex in enumerate(dataframe.index):
        dataframe.loc[idex,'linear']=acclinear[number]
        dataframe.loc[idex,'svrl']=accsvrl[number]
        dataframe.loc[idex,'svrnl']=accsvrnl[number]
        dataframe.loc[idex,'decisionReg']=accdes[number]
        dataframe.loc[idex,'randomForestReg']=accrf[number]
        return dataframe

In [165]:
# main program 
data_original = pd.read_csv('preprocessed_CKD.csv')
data_ckd= data_original
data_ckd

data_ckd=pd.get_dummies(data_ckd,drop_first=True,dtype=int)
data_ckd.head()

# ip op split 
indep_x=data_ckd.drop(['classification_notckd'],axis=1)
dep_y = data_ckd['classification_notckd']

# feature selection 
no_of_features= 20
kBest=selectkbest(indep_x,dep_y,no_of_features)

acclinear=[]
accsvrl=[]
accsvrnl=[]
accdes=[]
accrf=[]

x_train,x_test,y_train,y_test=split_scaler(kBest,dep_y)

# algorithms 
r2=linear(x_train,y_train,x_test)
acclinear.append(r2)
r2=svrl(x_train,y_train,x_test)
accsvrl.append(r2)
r2=svrnl(x_train,y_train,x_test)
accsvrnl.append(r2)
r2=decisionReg(x_train,y_train,x_test)
accdes.append(r2)
r2=randomForestReg(x_train,y_train,x_test)
accrf.append(r2)



result_regression = select_k_regression(acclinear,accsvrl,accsvrnl,accdes,accrf)

In [154]:
result_regression  #5

              linear      svrl     svrnl decisionReg randomForestReg
chi square  0.434757  0.335114  0.765607    0.835165        0.892308

In [156]:
result_regression #4

              linear      svrl     svrnl decisionReg randomForestReg
chi square  0.423816  0.331827  0.719794     0.78022         0.80989

In [159]:
result_regression  #3

              linear      svrl     svrnl decisionReg randomForestReg
chi square  0.219165  0.065709  0.403994    0.395604        0.497802

In [161]:
result_regression #6

              linear      svrl     svrnl decisionReg randomForestReg
chi square  0.662008  0.630609  0.867306    0.835165        0.925275

In [163]:
result_regression #8

              linear      svrl     svrnl decisionReg randomForestReg
chi square  0.759325  0.760679  0.919424     0.89011        0.958791

In [164]:
result_regression #10

              linear      svrl     svrnl decisionReg randomForestReg
chi square  0.759325  0.760679  0.919424     0.89011        0.958791

In [166]:
result_regression #20

             linear      svrl     svrnl decisionReg randomForestReg
chi square  0.74239  0.705051  0.929833    0.945055        0.880769

I applied feature selection using SelectKBest on the CKD dataset and experimented with regression models. However, since CKD prediction is a classification problem, regression models are not appropriate for this task. Although performance appeared to improve with an increasing number of features, the results are not reliable for evaluation. Therefore, classification models are more suitable, and feature selection should be evaluated using classification metrics such as accuracy, precision, recall, and F1-score