## regression problem - salary prediction of MBA placement dataset  
### with feature selection, standardization, data preprocessing and deployment

In [76]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_regression
from sklearn.feature_selection import RFE
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import pickle

In [77]:
# feature selection
def selectkbest(indep_x,dep_y,n):
    test=SelectKBest(score_func=f_regression,k=n)
    fit1=test.fit(indep_x,dep_y)    # fit - learns which features are important features 
    seleted_features=fit1.transform(indep_x)     #transform - select those features 
    # seleted_features = test.fit_transform(indep_x,dep_y)        # fit & transform in one step 
    return seleted_features, fit1

# tran test split and standardization 
def split_scaler(indep_x,dep_y):
    x_train,x_test,y_train,y_test = train_test_split(indep_x,dep_y,test_size=0.20,random_state=0)
    # standardization - Input X
    sc=StandardScaler()
    x_train=sc.fit_transform(x_train)
    x_test=sc.transform(x_test)
    pickle.dump(sc,open("x_mba_scaler","wb"))   # saving the X i/p standardization in a file 
    return  x_train,x_test,y_train,y_test

# regression model predict & evaluation 
def r2_score_pred(regressor,x_test,y_test):
    y_pred=regressor.predict(x_test)
    from sklearn.metrics import r2_score
    r2_score=r2_score(y_test,y_pred)
    return r2_score 

# regression algorithms 
# linear
def linear(x_train,y_train,x_test):
    from sklearn.linear_model import LinearRegression
    regressor=LinearRegression()
    regressor.fit(x_train,y_train)
    r2 = r2_score_pred(regressor,x_test,y_test)
    return r2 
    
# SVR -linear
def svrl(x_train,y_train,x_test):
    from sklearn.svm import SVR
    regressor=SVR(kernel='linear')
    regressor.fit(x_train,y_train)
    r2 = r2_score_pred(regressor,x_test,y_test)
    return r2 
    
# SVR-non linear
def svrnl(x_train,y_train,x_test):
    from sklearn.svm import SVR
    regressor=SVR(kernel='rbf')
    regressor.fit(x_train,y_train)
    r2 = r2_score_pred(regressor,x_test,y_test)
    return r2 
    
# decision tree
def decisionReg(x_train,y_train,x_test):
    from sklearn.tree import DecisionTreeRegressor
    regressor=DecisionTreeRegressor(criterion='squared_error',random_state=0)
    regressor.fit(x_train,y_train)
    r2 = r2_score_pred(regressor,x_test,y_test)
    return r2 
    
# random forest 
def randomForestReg(x_train,y_train,x_test):
    from sklearn.ensemble import RandomForestRegressor
    regressor=RandomForestRegressor(n_estimators=10,random_state=0)
    regressor.fit(x_train,y_train)
    r2 = r2_score_pred(regressor,x_test,y_test)
    return r2 


# select features table 
def select_k_regression(acclinear,accsvrl,accsvrnl,accdes,accrf):
    dataframe=pd.DataFrame(index=['r_regression'],columns=['linear','svrl','svrnl','decisionReg','randomForestReg'])
    for number,idex in enumerate(dataframe.index):
        dataframe.loc[idex,'linear']=acclinear[number]
        dataframe.loc[idex,'svrl']=accsvrl[number]
        dataframe.loc[idex,'svrnl']=accsvrnl[number]
        dataframe.loc[idex,'decisionReg']=accdes[number]
        dataframe.loc[idex,'randomForestReg']=accrf[number]
        return dataframe

In [78]:
data_original = pd.read_csv('preproc_placement.csv')
data_mba= data_original
data_mba

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,0.0
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,0.0

In [79]:
data_mba=pd.get_dummies(data_mba,drop_first=True,dtype=int)
data_mba.head()

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary,gender_M,ssc_b_Others,hsc_b_Others,hsc_s_Commerce,hsc_s_Science,degree_t_Others,degree_t_Sci&Tech,workex_Yes,specialisation_Mkt&HR,status_Placed
0,1,67.00,91.00,58.00,55.0,58.80,270000.0,1,1,1,1,0,0,1,0,1,1
1,2,79.33,78.33,77.48,86.5,66.28,200000.0,1,0,1,0,1,0,1,1,0,1
2,3,65.00,68.00,64.00,75.0,57.80,250000.0,1,0,0,0,0,0,0,0,0,1
3,4,56.00,52.00,52.00,66.0,59.43,0.0,1,0,0,0,1,0,1,0,1,0
4,5,85.80,73.60,73.30,96.8,55.50,425000.0,1,0,0,1,0,0,0,0,0,1

In [80]:
# ip op split 
indep_x=data_mba.drop('salary',axis=1)
dep_y = data_mba['salary']

In [81]:
indep_x.head()

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,gender_M,ssc_b_Others,hsc_b_Others,hsc_s_Commerce,hsc_s_Science,degree_t_Others,degree_t_Sci&Tech,workex_Yes,specialisation_Mkt&HR,status_Placed
0,1,67.00,91.00,58.00,55.0,58.80,1,1,1,1,0,0,1,0,1,1
1,2,79.33,78.33,77.48,86.5,66.28,1,0,1,0,1,0,1,1,0,1
2,3,65.00,68.00,64.00,75.0,57.80,1,0,0,0,0,0,0,0,0,1
3,4,56.00,52.00,52.00,66.0,59.43,1,0,0,0,1,0,1,0,1,0
4,5,85.80,73.60,73.30,96.8,55.50,1,0,0,1,0,0,0,0,0,1

In [82]:
dep_y.head()

0    270000.0
1    200000.0
2    250000.0
3         0.0
4    425000.0
Name: salary, dtype: float64

In [83]:
# k best 
no_of_features = 4
kBest, fit1=selectkbest(indep_x,dep_y,no_of_features)
kBest

array([[67.  , 91.  , 58.  ,  1.  ],
       [79.33, 78.33, 77.48,  1.  ],
       [65.  , 68.  , 64.  ,  1.  ],
       [56.  , 52.  , 52.  ,  0.  ],
       [85.8 , 73.6 , 73.3 ,  1.  ],
       [55.  , 49.8 , 67.25,  0.  ],
       [46.  , 49.2 , 79.  ,  0.  ],
       [82.  , 64.  , 66.  ,  1.  ],
       [73.  , 79.  , 72.  ,  1.  ],
       [58.  , 70.  , 61.  ,  0.  ],
       [58.  , 61.  , 60.  ,  1.  ],
       [69.6 , 68.4 , 78.3 ,  1.  ],
       [47.  , 55.  , 65.  ,  0.  ],
       [77.  , 87.  , 59.  ,  1.  ],
       [62.  , 47.  , 50.  ,  0.  ],
       [65.  , 75.  , 69.  ,  1.  ],
       [63.  , 66.2 , 65.6 ,  1.  ],
       [55.  , 67.  , 64.  ,  0.  ],
       [63.  , 66.  , 64.  ,  0.  ],
       [60.  , 67.  , 70.  ,  1.  ],
       [62.  , 65.  , 66.  ,  1.  ],
       [79.  , 76.  , 85.  ,  1.  ],
       [69.8 , 60.8 , 72.23,  1.  ],
       [77.4 , 60.  , 64.74,  1.  ],
       [76.5 , 97.7 , 78.86,  1.  ],
       [52.58, 54.6 , 50.2 ,  0.  ],
       [71.  , 79.  , 66.  ,  1.  ],
       [63.  , 67.  , 66.  ,  1.  ],
       [76.76, 76.5 , 67.5 ,  1.  ],
       [62.  , 67.  , 58.  ,  0.  ],
       [64.  , 73.5 , 73.  ,  1.  ],
       [67.  , 53.  , 65.  ,  0.  ],
       [61.  , 81.  , 66.4 ,  1.  ],
       [87.  , 65.  , 81.  ,  1.  ],
       [62.  , 51.  , 52.  ,  0.  ],
       [69.  , 78.  , 72.  ,  1.  ],
       [51.  , 44.  , 57.  ,  0.  ],
       [79.  , 76.  , 65.6 ,  1.  ],
       [73.  , 58.  , 66.  ,  1.  ],
       [81.  , 68.  , 64.  ,  1.  ],
       [78.  , 77.  , 80.  ,  1.  ],
       [74.  , 63.16, 65.  ,  0.  ],
       [49.  , 39.  , 65.  ,  0.  ],
       [87.  , 87.  , 68.  ,  1.  ],
       [77.  , 73.  , 81.  ,  1.  ],
       [76.  , 64.  , 72.  ,  0.  ],
       [70.89, 71.98, 65.6 ,  0.  ],
       [63.  , 60.  , 57.  ,  1.  ],
       [63.  , 62.  , 68.  ,  1.  ],
       [50.  , 37.  , 52.  ,  0.  ],
       [75.2 , 73.2 , 68.4 ,  1.  ],
       [54.4 , 61.12, 56.2 ,  0.  ],
       [40.89, 45.83, 53.  ,  0.  ],
       [80.  , 70.  , 72.  ,  1.  ],
       [74.  , 60.  , 69.  ,  1.  ],
       [60.4 , 66.6 , 65.  ,  1.  ],
       [63.  , 71.4 , 61.4 ,  1.  ],
       [68.  , 76.  , 74.  ,  1.  ],
       [74.  , 62.  , 68.  ,  1.  ],
       [52.6 , 65.58, 72.11,  1.  ],
       [74.  , 70.  , 72.  ,  1.  ],
       [84.2 , 73.4 , 66.89,  1.  ],
       [86.5 , 64.2 , 67.4 ,  1.  ],
       [61.  , 70.  , 64.  ,  0.  ],
       [80.  , 73.  , 75.  ,  1.  ],
       [54.  , 47.  , 57.  ,  0.  ],
       [83.  , 74.  , 66.  ,  1.  ],
       [80.92, 78.5 , 67.  ,  1.  ],
       [69.7 , 47.  , 72.7 ,  0.  ],
       [73.  , 73.  , 66.  ,  1.  ],
       [82.  , 61.  , 62.  ,  1.  ],
       [75.  , 70.29, 71.  ,  1.  ],
       [84.86, 67.  , 78.  ,  1.  ],
       [64.6 , 83.83, 71.72,  1.  ],
       [56.6 , 64.8 , 70.2 ,  1.  ],
       [59.  , 62.  , 77.5 ,  0.  ],
       [66.5 , 70.4 , 71.93,  1.  ],
       [64.  , 80.  , 65.  ,  1.  ],
       [84.  , 90.9 , 64.5 ,  1.  ],
       [69.  , 62.  , 66.  ,  0.  ],
       [69.  , 62.  , 69.  ,  1.  ],
       [81.7 , 63.  , 67.  ,  1.  ],
       [63.  , 67.  , 74.  ,  0.  ],
       [84.  , 79.  , 68.  ,  1.  ],
       [70.  , 63.  , 70.  ,  1.  ],
       [83.84, 89.83, 77.2 ,  1.  ],
       [62.  , 63.  , 64.  ,  1.  ],
       [59.6 , 51.  , 60.  ,  0.  ],
       [66.  , 62.  , 73.  ,  1.  ],
       [84.  , 75.  , 69.  ,  1.  ],
       [85.  , 90.  , 82.  ,  1.  ],
       [52.  , 57.  , 50.8 ,  0.  ],
       [60.23, 69.  , 66.  ,  1.  ],
       [52.  , 62.  , 54.  ,  0.  ],
       [58.  , 62.  , 64.  ,  1.  ],
       [73.  , 78.  , 65.  ,  1.  ],
       [76.  , 70.  , 76.  ,  1.  ],
       [70.5 , 62.5 , 61.  ,  0.  ],
       [69.  , 73.  , 65.  ,  1.  ],
       [54.  , 82.  , 63.  ,  0.  ],
       [45.  , 57.  , 58.  ,  0.  ],
       [63.  , 72.  , 68.  ,  1.  ],
       [77.  , 61.  , 68.  ,  1.  ],
       [73.  , 78.  , 73.  ,  1.  ],
       [69.  , 63.  , 65.  ,  1.  ],
       [59.  , 64.  , 58.  ,  0.  ],
       [61.08, 50.  , 54.  ,  0.  ],
       [82.  , 90.  , 83.  ,  1.  ],
       [61.  , 82.  , 69.  ,  1.  ],
       [52.  , 63.  , 65.  ,  0.  ],
       [69.5 , 70.  , 72.  ,  1.  ],
       [51.  , 54.  , 61.  ,  0.  ],
       [58.  , 61.  , 61.  ,  1.  ],
       [73.96, 79.  , 67.  ,  1.  ],
       [65.  , 68.  , 69.  ,  1.  ],
       [73.  , 63.  , 66.  ,  1.  ],
       [68.2 , 72.8 , 66.6 ,  1.  ],
       [77.  , 75.  , 73.  ,  1.  ],
       [76.  , 80.  , 78.  ,  1.  ],
       [60.8 , 68.4 , 64.6 ,  1.  ],
       [58.  , 40.  , 59.  ,  0.  ],
       [64.  , 67.  , 69.6 ,  1.  ],
       [66.5 , 66.8 , 69.3 ,  1.  ],
       [74.  , 59.  , 73.  ,  1.  ],
       [67.  , 71.  , 64.33,  1.  ],
       [84.  , 73.  , 73.  ,  1.  ],
       [79.  , 61.  , 75.5 ,  1.  ],
       [72.  , 60.  , 69.  ,  1.  ],
       [80.4 , 73.4 , 77.72,  1.  ],
       [76.7 , 89.7 , 66.  ,  1.  ],
       [62.  , 65.  , 60.  ,  0.  ],
       [74.9 , 57.  , 62.  ,  1.  ],
       [67.  , 68.  , 64.  ,  1.  ],
       [73.  , 64.  , 77.  ,  1.  ],
       [77.44, 92.  , 72.  ,  1.  ],
       [72.  , 56.  , 69.  ,  1.  ],
       [47.  , 59.  , 64.  ,  0.  ],
       [67.  , 63.  , 72.  ,  1.  ],
       [82.  , 64.  , 73.  ,  1.  ],
       [77.  , 70.  , 59.  ,  1.  ],
       [65.  , 64.8 , 69.5 ,  1.  ],
       [66.  , 64.  , 60.  ,  0.  ],
       [85.  , 60.  , 73.43,  1.  ],
       [77.67, 64.89, 70.67,  1.  ],
       [52.  , 50.  , 61.  ,  0.  ],
       [89.4 , 65.66, 71.25,  1.  ],
       [62.  , 63.  , 66.  ,  1.  ],
       [70.  , 74.  , 65.  ,  1.  ],
       [77.  , 86.  , 56.  ,  1.  ],
       [44.  , 58.  , 55.  ,  0.  ],
       [71.  , 58.66, 58.  ,  1.  ],
       [65.  , 65.  , 75.  ,  1.  ],
       [75.4 , 60.5 , 84.  ,  1.  ],
       [49.  , 59.  , 65.  ,  1.  ],
       [53.  , 63.  , 60.  ,  1.  ],
       [51.57, 74.66, 59.9 ,  0.  ],
       [84.2 , 69.4 , 65.  ,  1.  ],
       [66.5 , 62.5 , 60.9 ,  1.  ],
       [67.  , 63.  , 64.  ,  0.  ],
       [52.  , 49.  , 58.  ,  0.  ],
       [87.  , 74.  , 65.  ,  1.  ],
       [55.6 , 51.  , 57.5 ,  0.  ],
       [74.2 , 87.6 , 77.25,  1.  ],
       [63.  , 67.  , 64.  ,  1.  ],
       [67.16, 72.5 , 63.35,  1.  ],
       [63.3 , 78.33, 74.  ,  0.  ],
       [62.  , 62.  , 60.  ,  1.  ],
       [67.9 , 62.  , 67.  ,  0.  ],
       [48.  , 51.  , 58.  ,  0.  ],
       [59.96, 42.16, 61.26,  0.  ],
       [63.4 , 67.2 , 60.  ,  0.  ],
       [80.  , 80.  , 72.  ,  1.  ],
       [73.  , 58.  , 56.  ,  1.  ],
       [52.  , 52.  , 55.  ,  0.  ],
       [73.24, 50.83, 64.27,  1.  ],
       [63.  , 62.  , 65.  ,  0.  ],
       [59.  , 60.  , 56.  ,  1.  ],
       [73.  , 97.  , 79.  ,  1.  ],
       [68.  , 56.  , 68.  ,  1.  ],
       [77.8 , 64.  , 64.2 ,  0.  ],
       [65.  , 71.5 , 62.8 ,  1.  ],
       [62.  , 60.33, 64.21,  0.  ],
       [52.  , 65.  , 57.  ,  0.  ],
       [65.  , 77.  , 69.  ,  1.  ],
       [56.28, 62.83, 59.79,  0.  ],
       [88.  , 72.  , 78.  ,  1.  ],
       [52.  , 64.  , 61.  ,  0.  ],
       [78.5 , 65.5 , 67.  ,  1.  ],
       [61.8 , 47.  , 54.38,  0.  ],
       [54.  , 77.6 , 69.2 ,  0.  ],
       [64.  , 70.2 , 61.  ,  0.  ],
       [67.  , 61.  , 72.  ,  1.  ],
       [65.2 , 61.4 , 64.8 ,  1.  ],
       [60.  , 63.  , 56.  ,  1.  ],
       [52.  , 55.  , 56.3 ,  0.  ],
       [66.  , 76.  , 72.  ,  1.  ],
       [72.  , 63.  , 77.5 ,  1.  ],
       [83.96, 53.  , 91.  ,  1.  ],
       [67.  , 70.  , 65.  ,  0.  ],
       [69.  , 65.  , 57.  ,  1.  ],
       [69.  , 60.  , 65.  ,  1.  ],
       [54.2 , 63.  , 58.  ,  0.  ],
       [70.  , 63.  , 66.  ,  1.  ],
       [55.68, 61.33, 56.87,  1.  ],
       [74.  , 73.  , 73.  ,  1.  ],
       [61.  , 62.  , 65.  ,  1.  ],
       [41.  , 42.  , 60.  ,  0.  ],
       [83.33, 78.  , 61.  ,  1.  ],
       [43.  , 60.  , 65.  ,  0.  ],
       [62.  , 72.  , 65.  ,  1.  ],
       [80.6 , 82.  , 77.6 ,  1.  ],
       [58.  , 60.  , 72.  ,  1.  ],
       [67.  , 67.  , 73.  ,  1.  ],
       [74.  , 66.  , 58.  ,  1.  ],
       [62.  , 58.  , 53.  ,  0.  ]])

In [84]:
indep_x.columns[fit1.get_support()]

Index(['ssc_p', 'hsc_p', 'degree_p', 'status_Placed'], dtype='object')

In [85]:
acclinear=[]
accsvrl=[]
accsvrnl=[]
accdes=[]
accrf=[]

x_train,x_test,y_train,y_test=split_scaler(kBest,dep_y)

# algorithms 
r2=linear(x_train,y_train,x_test)
acclinear.append(r2)
r2=svrl(x_train,y_train,x_test)
accsvrl.append(r2)
r2=svrnl(x_train,y_train,x_test)
accsvrnl.append(r2)
r2=decisionReg(x_train,y_train,x_test)
accdes.append(r2)
r2=randomForestReg(x_train,y_train,x_test)
accrf.append(r2)

result_regression = select_k_regression(acclinear,accsvrl,accsvrnl,accdes,accrf)

In [86]:
result_regression #4

                linear      svrl     svrnl decisionReg randomForestReg
r_regression  0.899295 -0.320522 -0.324558   -0.098962         0.87083

In [87]:
def linear(x_train,y_train,x_test):
    from sklearn.linear_model import LinearRegression
    regressor=LinearRegression()
    regressor.fit(x_train,y_train)
    r2 = r2_score_pred(regressor,x_test,y_test)
    return r2 

final_model =linear(x_train,y_train,x_test)
final_model

0.8992950766841188

# lINEAR REGRESSION 
## Machine Learning Pipeline with Automated Preprocessing + Model Selection

## linear model creation

In [90]:
data_original.head()

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,0.0
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0

In [91]:
data_original.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sl_no           215 non-null    int64
 1   gender          215 non-null    object
 2   ssc_p           215 non-null    float64
 3   ssc_b           215 non-null    object
 4   hsc_p           215 non-null    float64
 5   hsc_b           215 non-null    object
 6   hsc_s           215 non-null    object
 7   degree_p        215 non-null    float64
 8   degree_t        215 non-null    object
 9   workex          215 non-null    object
 10  etest_p         215 non-null    float64
 11  specialisation  215 non-null    object
 12  mba_p           215 non-null    float64
 13  status          215 non-null    object
 14  salary          215 non-null    float64
dtypes: float64(6), int64(1), object(8)
memory usage: 25.3+ KB

In [92]:
# input output split 
X=data_original.drop(['salary','sl_no'], axis=1)
Y=data_original['salary']

In [93]:
# train test split 
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.30,random_state=42)

In [94]:
# column identification
categorical_cols = X.select_dtypes(include=['object']).columns
print(categorical_cols)
numerical_cols = X.select_dtypes(exclude=['object']).columns
print(numerical_cols)

Index(['gender', 'ssc_b', 'hsc_b', 'hsc_s', 'degree_t', 'workex',
       'specialisation', 'status'],
      dtype='object')
Index(['ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p'], dtype='object')

In [100]:
# preprocessing  -  for input
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
preprocessor = ColumnTransformer(
    transformers=[('cat',OneHotEncoder(drop='first',handle_unknown='ignore'), categorical_cols ),
                 ('num',"passthrough" ,numerical_cols )
    ]
)
preprocessor

ColumnTransformer(transformers=[('cat',
                                 OneHotEncoder(drop='first',
                                               handle_unknown='ignore'),
                                 Index(['gender', 'ssc_b', 'hsc_b', 'hsc_s', 'degree_t', 'workex',
       'specialisation', 'status'],
      dtype='object')),
                                ('num', 'passthrough',
                                 Index(['ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p'], dtype='object'))])

In [103]:
# Pipeline --> feature selection + model creation 
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import SelectKBest, f_regression
from sklearn.linear_model import LinearRegression
pipeline = Pipeline(
    [
        ("preprocessing",preprocessor),
        ("scaling",StandardScaler()),
        ("feature_selection",SelectKBest(score_func=f_regression,k=4)),
        ("model",LinearRegression())
    ]
)
pipeline

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore'),
                                                  Index(['gender', 'ssc_b', 'hsc_b', 'hsc_s', 'degree_t', 'workex',
       'specialisation', 'status'],
      dtype='object')),
                                                 ('num', 'passthrough',
                                                  Index(['ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p'], dtype='object'))])),
                ('scaling', StandardScaler()),
                ('feature_selection',
                 SelectKBest(k=4,
                             score_func=<function f_regression at 0x000001BD4CF82B60>)),
                ('model', LinearRegression())])

In [104]:

# model creation
pipeline.fit(x_train,y_train)
y_predicted = pipeline.predict(x_test)

# model evaluation 
from sklearn.metrics import r2_score
r_score = r2_score(y_test,y_predicted)
print("regression accuracy: ", r_score)

regression accuracy:  0.7839540966215024

Data leakage prevention

Pipelines correctly separate train/test transformations.

In manual preprocessing, you might have accidentally fit scalers/encoders on the full dataset, which can inflate accuracy.

The pipeline’s lower score may actually be the true generalization performance.

In [109]:
# gender	ssc_p	ssc_b	hsc_p	hsc_b	hsc_s	degree_p	degree_t	workex	etest_p	specialisation	mba_p	status	salary
# M	67.00	Others	91.00	Others	Commerce	58.00	Sci&Tech	No	55.0	Mkt&HR	58.80	Placed	270000.0

# Predict with raw categorical input
user_input = pd.DataFrame({"gender":['M'],
                           "ssc_p":[67.00],
                           "ssc_b":['Others'],
                           "hsc_p":[91.00],
                           "hsc_b":['Others'],
                           "hsc_s":['Commerce'],
                           "degree_p":[58.00],
                           "degree_t":['Sci&Tech'],
                           "workex":['No'],
                           "etest_p":[55.0],
                           "specialisation":['Mkt&HR'],
                           "mba_p":[58.80],
                           "status":['Placed']
                            })
print(pipeline.predict(user_input))

[309802.16134968]